version: 2
updates:
  # Hugo modules (Go dependencies)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
    reviewers:
      - "ScrambledBits"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "ScrambledBits"
    commit-message:
      prefix: "chore"
      include: "scope"

  # NPM dependencies (if package.json exists)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "ScrambledBits"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]